# Traer todas las frutas
GET http://127.0.0.1:5000/frutas

###

# Traer fruta por id
GET http://127.0.0.1:5000/frutas/4

###

# Traer fruta por nombre
GET http://127.0.0.1:5000/frutas/nombre/Manzanas

###

# Traer fruta con importe mayor a 300
GET http://127.0.0.1:5000/frutas/precio/300